server:
  port: 8082

spring:
  application:
    name: visitor-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/visitordb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka