name: apartment_holder_app
description: Apartment Holder App for Visitor Management

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.15.1
  firebase_messaging: ^14.7.1
  firebase_storage: ^11.0.16
  qr_flutter: ^4.0.0
  image_picker: ^0.8.9
  intl: ^0.18.1
  share_plus: ^7.0.1
  flutter_local_notifications: ^19.2.1
  provider: ^6.0.5
  datetime_picker_formfield: ^2.0.1
  fluttertoast: ^8.2.1 # safer version for Flutter 3.22+

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6 # optional, useful if you use json_serializable

flutter:
  uses-material-design: true

  assets:
    - assets/ # Make sure this folder exists and is not empty
