server:
  port: 8084

spring:
  application:
    name: security-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/securitydb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka