server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/userdb # Or Firebase config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka